### ISSUE TITLE
Incompat With Alternate current backport

### ISSUE THREAD

**Issue by quentin452** [quentin452/RecurrentComplex#11]
```
java.lang.NullPointerException: Exception getting block type in world
	at net.minecraft.block.BlockRedstoneWire.handler$zzc000$onPlace(BlockRedstoneWire.java:584)
	at net.minecraft.block.BlockRedstoneWire.func_149726_b(BlockRedstoneWire.java:195)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at ivorius.reccomplex.structures.StructureSpawnContext.setBlock(StructureSpawnContext.java:105)
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:163)
	at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:49)
	at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:99)
	at ivorius.reccomplex.worldgen.StructureGenerator.randomInstantly(StructureGenerator.java:78)
	at ivorius.reccomplex.worldgen.WorldGenStructures.generate(WorldGenStructures.java:84)
	at ivorius.reccomplex.events.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:61)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_303_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at matthbo.mods.darkworld.world.ChunkProviderDarkWorldBeta.func_73153_a(ChunkProviderDarkWorldBeta.java:424)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at atomicstryker.battletowers.common.AS_WorldGenTower.getSurfaceBlockHeight(AS_WorldGenTower.java:511)
	at atomicstryker.battletowers.common.AS_WorldGenTower.getChosenTowerOrdinal(AS_WorldGenTower.java:44)
	at atomicstryker.battletowers.common.WorldGenHandler.attemptToSpawnTower(WorldGenHandler.java:137)
	at atomicstryker.battletowers.common.WorldGenHandler.generateSurface(WorldGenHandler.java:125)
	at atomicstryker.battletowers.common.WorldGenHandler.generate(WorldGenHandler.java:84)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by quentin452** [comment]
It seem thats a bug caused by an another mod,not recurrent complex

**Comment by quentin452** [comment]
Now i have this list of suspects : 
![image](https://github.com/quentin452/RecurrentComplex/assets/42176772/7341d832-e0f7-449a-8ce0-60d05e43581a)

**Comment by quentin452** [comment]
Ok so i found the incompat , its caused by alternate current

**Comment by quentin452** [comment]
Instance that to reproduce the bug with instructions : https://github.com/quentin452/alternate-current-backport](https://mega.nz/folder/6gkXSLAb#GjRL1KNR8-SWo05-gxIKIg

the mod : https://github.com/quentin452/alternate-current-backport
